package com.service.entity;

public enum CategoryType {

	AUTOMOBILES,
	POWER_GENERATION,
	CEMENT,
	CHEMICALS_AND_FERTILISERS,
	SOLAR_ENERGY,
	SUGAR_INDUSTRY,
	BATTERY_AND_ENERGY,
	PAPER_AND_PULP,
	PHARMACEUTICALES,
	FIRE_AND_SAFETY,
	MAHADISCOM,
	REFINERIES_AND_PERTROCHEMICALS,
	SOFT_BEVERAGES,
	METALS,
	MODERN_AGRICULTURE,
	TEXTILE;

	
}
